import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 中文文档（docs/docs/zh/）：自动生成侧边栏，读取各目录 _category_.json 的中文标签
  zhSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
